apiVersion: apps/v1
kind: Deployment
metadata:
  name: internship-front
spec:
  selector:
    matchLabels:
      app: internship-front
  replicas: 1
  template:
    metadata:
      labels:
        app: internship-front
    spec:
      containers:
        - name: internship-front
          image: chxws/testcntt:latest
          ports:
            - containerPort: 80
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: internship-front-svc
spec:
  selector:
    app: internship-front
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
  type: LoadBalancer # type of the service.

