apiVersion: apps/v1
kind: Deployment
metadata:
  name: internship-front
spec:
  selector:
    matchLabels:
      app: internship-front
  replicas: 1
  template:
    metadata:
      labels:
        app: internship-front
    spec:
      containers:
        - name: internship-front
          image: chxws/internship-app-front:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: internship-front-svc
spec:
  selector:
    app: internship-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer # type of the service.
